name: ads
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  dependencies:
  adaptive_theme: ^2.2.0
  firebase_messaging:
  awesome_notifications:
  flutter_downloader:
  banner_carousel: ^1.2.1
  basic_utils: ^3.3.3
  carousel_slider: ^2.3.1
  contained_tab_bar_view: ^0.7.1
  cool_alert: ^1.0.3
  http:
  font_awesome_flutter: ^8.12.0
  country_picker: ^2.0.6
  cupertino_icons: ^1.0.0
  custom_clippers: ^1.0.0
  dartx: ^0.7.1
  dotted_border: ^2.0.0
  dotted_line: ^2.0.2
  double_back_to_close: ^2.0.0
  expand_widget: ^2.1.0
  firebase_auth: ^2.0.0
  firebase_chat: ^0.0.4
  flag: ^3.1.0
  flutter:
    sdk: flutter
  flutter_form_builder: ^6.1.0+1
  flutter_icons: ^1.0.0+1
  flutter_inappwebview: ^5.3.2
  flutter_localizations:
    sdk: flutter
  flutter_onboard: ^1.0.3
  flutter_rating_bar: ^4.0.0
  flutter_staggered_animations: ^0.1.2
  fluttertoast: ^8.0.8
  glass: ^1.0.1+1
  glass_kit: ^2.0.1
  google_fonts: ^2.1.0
  google_maps_flutter: ^2.0.10
  google_nav_bar: ^5.0.3
  google_places_flutter: ^2.0.3
  group_radio_button: ^1.0.1
  i18n_extension: ^4.0.0
  image_picker: ^0.8.1+4
  in_app_review: ^2.0.2
  inspection: ^0.0.12
  jiffy: ^3.0.1
  line_icons: ^0.2.0
  location: ^4.3.0
  map_launcher: ^1.1.2
  masonry_grid: ^1.0.0
  measure_size: ^2.0.0
  package_info: ^2.0.2
  pin_code_fields: ^6.1.0
  pretty_dio_logger: ^1.1.1
  provider: ^5.0.0
  pull_to_refresh: ^1.6.4
  qr_code_scanner: ^0.5.2
  qr_flutter: ^4.0.0
  random_string: ^2.1.0
  rx_shared_preferences: ^2.1.0
  share: ^2.0.1
  shared_preferences: ^2.0.6
  singleton: ^0.0.2
  sliding_up_panel: ^2.0.0+1
  smooth_page_indicator: ^0.2.3
  stacked: ^1.7.6
  sticky_headers: ^0.1.8+1
  supercharged: ^2.0.0
  ticketview: ^1.0.0
  timelines: ^0.1.0
  url_launcher: ^6.0.9
  velocity_x: ^3.3.0
  video_player: ^1.0.1
  what3words: ^3.0.4
dependency_overrides:
  dio: ^4.0.0
  firebase_chat: 0.0.4
  cloud_firestore: ^1.0.3
  flutter_svg: ^0.22.0
  geocoder:
  google_maps_flutter: ^2.0.6
  intl: ^0.17.0
  args: ^2.0.0
  flutter_application_id: ^1.0.0
  flutter_polyline_points: ^0.2.4
  rxdart: ^0.27.1
  yaml: ^3.1.0
  equatable: ^2.0.0
  plugin_platform_interface: ^2.0.0
  #####################
  url_launcher: ^5.7.10
  flutter_share: ^1.0.5
  font_awesome_flutter: ^8.12.0
  file_picker:
  flutter_datetime_picker: ^1.5.1
  flutter_html: null
  carousel_pro: ^1.0.0
  numberpicker: ^1.3.0
  panorama: ^0.4.1
  ###########social#############
  get: ^3.10.2
  signal_strength_indicator: null
  convex_bottom_bar: null
  permission_handler: null

dev_dependencies:
  flutter_application_id: "^1.0.0"
  flutter_launcher_icons: "^0.9.0"
  flutter_native_splash: ^1.2.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
    # assets:
    # - assets/images/
    # - assets/locales/
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
